name: Latest blog post workflow
on: 
    # Runs every day at 2am (see https://crontab.guru/#0_2_*_*_*)
    schedule:
        - cron: '0 2 * * *'

    # Enable manual trigger
    workflow_dispatch:
        input:
            tags:
                description: 'Tags to label this manual run (optional)'
                default: 'Manual run'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "4"
                feed_list: "https://feeds.feedburner.com/miguelgfierro"