name: Latest Substack Posts Workflow
on: 
    schedule:
        - cron: '0 2 * * *'
    workflow_dispatch:

jobs:
    update-readme-with-substack:
        name: Update this repo's README with latest Substack posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Fetch Substack posts from RSS2JSON
              run: |
                curl "https://api.rss2json.com/v1/api.json?rss_url=https://miguelgfierro.substack.com/feed" > substack.json
            - name: Parse and update README
              run: |
                # Extract the latest posts from JSON and format them for the README
                cat substack.json | jq -r '.items[] | "- 🔥 [\(.title)](\(.link))"' | head -n 4 > latest_posts.md
            - name: Replace posts in README
              run: |
                # Read the latest posts from the file into a variable
                posts=$(cat latest_posts.md | sed ':a;N;$!ba;s/\n/\\n/g; s/[&/]/\\&/g')
                # Safely replace the section in README with the latest posts
                sed -i '/<!-- LATEST_POSTS_START -->/,/<!-- LATEST_POSTS_END -->/c\<!-- LATEST_POSTS_START -->\n'"$posts"'\n<!-- LATEST_POSTS_END -->' README.md
            - name: Clean up temporary files
              run: |
                rm latest_posts.md substack.json
            - name: Commit changes
              run: |
                git config --global user.name "github-actions"
                git config --global user.email "github-actions@github.com"
                git add README.md
                git commit -m "Update latest Substack posts"
                git push
