name: Latest Substack Posts Workflow
on: 
    schedule:
        - cron: '0 2 * * *'
    workflow_dispatch:

jobs:
    update-readme-with-substack:
        name: Update this repo's README with latest Substack posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Fetch Substack posts from RSS2JSON
              run: |
                curl "https://api.rss2json.com/v1/api.json?rss_url=https://miguelgfierro.substack.com/feed" > substack.json
            - name: Parse and update README
              run: |
                # Extract the latest posts from JSON and format them for the README
                cat substack.json | jq -r '.items[] | "- 🔥 [\(.title)](\(.link))"' | head -n 4 > latest_posts.md
            - name: Replace posts in README
              run: |
                # Read the content of latest_posts.md into a variable
                posts=$(cat latest_posts.md)
                # Use awk to safely replace the section between the markers
                awk -v posts="$posts" '
                  BEGIN { print_flag = 1 }
                  /<!-- BLOG-POST-LIST:START -->/ { print_flag = 0; print $0; print posts; next }
                  /<!-- BLOG-POST-LIST:END -->/ { print_flag = 1 }
                  print_flag == 1 { print $0 }
                ' README.md > README.tmp && mv README.tmp README.md
            - name: Clean up temporary files
              run: |
                cat latest_posts.md
                rm latest_posts.md substack.json
            - name: Check for changes in README
              run: |
                if ! git diff --quiet README.md; then
                  echo "README.md has changed"
                  git config --global user.name "github-actions"
                  git config --global user.email "github-actions@github.com"
                  git add README.md
                  git commit -m "Update latest Substack posts"
                  git push
                else
                  echo "No changes to commit"
                  exit 0
                fi
                
